### PR TITLE
Implementing BEM naming pattern in views

### PR DESCRIPTION
**Pull request by JonasThers**

### CODE REVIEW

**Comment by valscion** [comment]
Should we also migrate all the existing styles to use only these BEM CSS class names and not element selectors?

**Comment by JonasThers** [comment]
Yes, I can do that

**Review by valscion — CHANGES_REQUESTED** [review]
Oops this doesn't make that much sense, sorry for the bad writing on the card! 😳

**Comment by valscion** [comment]
Superceded by https://github.com/venuu/video-game-database-ruby/pull/22

**Review by Angel-cuba — COMMENTED** [review]
Nice!

**Pull request closed without merging**
